# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-29 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180301_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmdbciip',
            name='cmdb_ci',
        ),
        migrations.RemoveField(
            model_name='cmdbcisoft',
            name='cmdb_ci',
        ),
        migrations.DeleteModel(
            name='CmdbCi',
        ),
        migrations.DeleteModel(
            name='CmdbCiIp',
        ),
        migrations.DeleteModel(
            name='CmdbCiSoft',
        ),
    ]
